# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

aliases:
  - &restore-cache-deps
      key: dependency-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}-2.1
  - &save-cache-deps
      key: dependency-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}-2.1
      paths:
        - node_modules

defaults: &defaults
  working_directory: ~/really-code-configurator
  docker:
    - image: circleci/node:8-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-deps
      - run:
          name: Git Log
          command: |
            if [ -z "$(git describe --exact-match HEAD)" ]; then
              echo "Not tagged commit"
            fi

            if [ -z "$(git log --format=%B -n 1 | grep -iE '^[0-9]+[.]{1,}[0-9]+[.]{1,}[0-9]+$')" ]; then
              echo "No tag/ version in commit message"
            fi
      - run:
          name: Install Global Dependencies
          command: sudo npm i -g npm@latest --quiet
      - run:
          name: Install Dependencies
          command: npm ci --quiet
      - save_cache: *save-cache-deps
      - run:
          name: Versions
          command: node -v && npm version && which npm && pwd
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run ts
      - persist_to_workspace:
          root: ~/really-code-configurator
          paths:
            - "*"

  test_local:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/really-code-configurator
      - run:
          name: Test
          command: npx -p web-component-tester -- npm run test:ci

  test_ie_11:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/really-code-configurator
      - run:
          name: Test (Internet Explorer 11)
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ] && [ -z "$(git describe --exact-match HEAD)" ] && [ -z "$(git log --format=%B -n 1 | grep -iE '^[0-9]+[.]{1,}[0-9]+[.]{1,}[0-9]+$')" ]; then
              npx -p web-component-tester -- npm run test:sl -- -s 'windows 7/internet explorer@11';
            fi

  test_edge:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/really-code-configurator
      - run:
          name: Test (Edge 17, 13)
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ] && [ -z "$(git describe --exact-match HEAD)" ] && [ -z "$(git log --format=%B -n 1 | grep -iE '^[0-9]+[.]{1,}[0-9]+[.]{1,}[0-9]+$')" ]; then
              npx -p web-component-tester -- npm run test:sl -- -s 'windows 10/microsoftedge@17' -s 'windows 10/microsoftedge@13';
            fi

  test_safari:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/really-code-configurator
      - run:
          name: Test (Safari 10.1, 9)
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ] && [ -z "$(git describe --exact-match HEAD)" ] && [ -z "$(git log --format=%B -n 1 | grep -iE '^[0-9]+[.]{1,}[0-9]+[.]{1,}[0-9]+$')" ]; then
              npx -p web-component-tester -- npm run test:sl -- -s 'macos 10.12/safari@10.1' -s 'os x 10.11/safari@9';
            fi

  test_chrome:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/really-code-configurator
      - run:
          name: Test (Chrome 69, 41)
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ] && [ -z "$(git describe --exact-match HEAD)" ] && [ -z "$(git log --format=%B -n 1 | grep -iE '^[0-9]+[.]{1,}[0-9]+[.]{1,}[0-9]+$')" ]; then
              npx -p web-component-tester -- npm run test:sl -- -s 'windows 10/chrome@69' -s 'Linux/chrome@41';
            fi

  test_firefox:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/really-code-configurator
      - run:
          name: Test (Firefox 63, 62)
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ] && [ -z "$(git describe --exact-match HEAD)" ] && [ -z "$(git log --format=%B -n 1 | grep -iE '^[0-9]+[.]{1,}[0-9]+[.]{1,}[0-9]+$')" ]; then
              npx -p web-component-tester -- npm run test:sl -- -s 'windows 10/firefox@63' -s 'macos 10.14/firefox@62';
            fi

workflows:
  version: 2
  multi-build-n-test:
    jobs:
      - build
      - test_local:
          requires:
            - build

      - test_ie_11:
          requires:
            - build

      - test_edge:
          requires:
            - build

      - test_safari:
          requires:
            - build

      - test_chrome:
          requires:
            - build

      - test_firefox:
          requires:
            - build
